//
//  LangDescriptor.swift
//  Coda
//
//  Created by Matoi on 14.02.2023.
//


import SwiftUI

enum LangDescriptor: String, Identifiable {
    
    var id: UUID { UUID() }
    
    static var defaultValue: Self = .None
    
    static var allLanguages: [Self] = [
                                                  .None,
                                                  .ABAP,
                                                  .ABC,
                                                  .ActionScript,
                                                  .Ada,
                                                  .AgilentVEE,
                                                  .Algol,
                                                  .Alice,
                                                  .Angelscript,
                                                  .Apex,
                                                  .APL,
                                                  .AppleScript,
                                                  .Arc,
                                                  .Arduino,
                                                  .ASP,
                                                  .AspectJ,
                                                  .Assembly,
                                                  .ATLAS,
                                                  .Augeas,
                                                  .AutoHotkey,
                                                  .AutoIt,
                                                  .AutoLISP,
                                                  .Automator,
                                                  .Avenue,
                                                  .Awk,
                                                  .Bash,
                                                  .VisualBasic,
                                                  .bc,
                                                  .BCPL,
                                                  .BETA,
                                                  .BlitzMax,
                                                  .Boo,
                                                  .BourneShell,
                                                  .Bro,
                                                  .C,
                                                  .CShell,
                                                  .CSharp,
                                                  .CPP,
                                                  .CPP_CLI,
                                                  .COmega,
                                                  .Caml,
                                                  .Ceylon,
                                                  .CFML,
                                                  .cg,
                                                  .Ch,
                                                  .CHILL,
                                                  .CIL,
                                                  .CL,
                                                  .Clarion,
                                                  .Clean,
                                                  .Clipper,
                                                  .Clojure,
                                                  .CLU,
                                                  .COBOL,
                                                  .Cobra,
                                                  .CoffeeScript,
                                                  .ColdFusion,
                                                  .COMAL,
                                                  .CommonLisp,
                                                  .Coq,
                                                  .cT,
                                                  .Curl,
                                                  .D,
                                                  .Dart,
                                                  .DCL,
                                                  .DCPU_ASM,
                                                  .Delphi_ObjectPascal,
                                                  .DiBOL,
                                                  .Dylan,
                                                  .E,
                                                  .eC,
                                                  .Ecl,
                                                  .ECMAScript,
                                                  .EGL,
                                                  .Eiffel,
                                                  .Elixir,
                                                  .EmacsLisp,
                                                  .Erlang,
                                                  .Etoys,
                                                  .Euphoria,
                                                  .EXEC,
                                                  .FSharp,
                                                  .Factor,
                                                  .Falcon,
                                                  .Fancy,
                                                  .Fantom,
                                                  .Felix,
                                                  .Forth,
                                                  .Fortran,
                                                  .Fortress,
                                                  .VisualFoxPro,
                                                  .Gambas,
                                                  .GNUOctave,
                                                  .Go,
                                                  .GoogleAppsScript,
                                                  .Gosu,
                                                  .Groovy,
                                                  .Haskell,
                                                  .haXe,
                                                  .Heron,
                                                  .HPL,
                                                  .HyperTalk,
                                                  .Icon,
                                                  .IDL,
                                                  .Inform,
                                                  .InformixGL,
                                                  .INTERCAL,
                                                  .Io,
                                                  .Ioke,
                                                  .J,
                                                  .JSharp,
                                                  .JADE,
                                                  .Java,
                                                  .JavaFXScript,
                                                  .JavaScript,
                                                  .JScript,
                                                  .JScriptNET,
                                                  .Julia,
                                                  .KornShell,
                                                  .Kotlin,
                                                  .LabVIEW,
                                                  .LadderLogic,
                                                  .Lasso,
                                                  .Limbo,
                                                  .Lingo,
                                                  .Lisp,
                                                  .Logo,
                                                  .Logos,
                                                  .Logtalk,
                                                  .LotusScript,
                                                  .LPC,
                                                  .Lua,
                                                  .Lustre,
                                                  .M4,
                                                  .MAD,
                                                  .Magic,
                                                  .Magik,
                                                  .Malbolge,
                                                  .MANTIS,
                                                  .Maple,
                                                  .Mathematica,
                                                  .MATLAB,
                                                  .Max_MSP,
                                                  .MAXScript,
                                                  .MEL,
                                                  .Mercury,
                                                  .Mirah,
                                                  .Miva,
                                                  .ML,
                                                  .Monkey,
                                                  .ModulaTwo,
                                                  .ModulaThree,
                                                  .MOO,
                                                  .Moto,
                                                  .MSDOSBatch,
                                                  .MUMPS,
                                                  .NATURAL,
                                                  .Nemerle,
                                                  .Nimrod,
                                                  .NQC,
                                                  .NSIS,
                                                  .Nu,
                                                  .NXTG,
                                                  .Oberon,
                                                  .ObjectRexx,
                                                  .ObjectiveC,
                                                  .ObjectiveJ,
                                                  .OCaml,
                                                  .Occam,
                                                  .ooc,
                                                  .Opa,
                                                  .OpenCL,
                                                  .OpenEdgeABL,
                                                  .OPL,
                                                  .Oz,
                                                  .Paradox,
                                                  .Parrot,
                                                  .Pascal,
                                                  .Perl,
                                                  .PHP,
                                                  .Pike,
                                                  .PILOT,
                                                  .PL_I,
                                                  .PL_SQL,
                                                  .Pliant,
                                                  .PostScript,
                                                  .POV_Ray,
                                                  .PowerBasic,
                                                  .PowerScript,
                                                  .PowerShell,
                                                  .Processing,
                                                  .Prolog,
                                                  .Puppet,
                                                  .PureData,
                                                  .Python,
                                                  .Q,
                                                  .R,
                                                  .Racket,
                                                  .REALBasic,
                                                  .REBOL,
                                                  .Revolution,
                                                  .REXX,
                                                  .RPG,
                                                  .Ruby,
                                                  .Rust,
                                                  .S,
                                                  .S_PLUS,
                                                  .SAS,
                                                  .Sather,
                                                  .Scala,
                                                  .Scheme,
                                                  .Scilab,
                                                  .Scratch,
                                                  .sed,
                                                  .Seed7,
                                                  .Slf,
                                                  .Shell,
                                                  .SIGNAL,
                                                  .Simula,
                                                  .Simulink,
                                                  .Slate,
                                                  .Smalltalk,
                                                  .Smarty,
                                                  .SPARK,
                                                  .SPSS,
                                                  .SQR,
                                                  .Squeak,
                                                  .Squirrel,
                                                  .StandardML,
                                                  .Suneido,
                                                  .SuperCollider,
                                                  .Swift,
                                                  .TACL,
                                                  .Tcl,
                                                  .Tex,
                                                  .thinBasic,
                                                  .TOM,
                                                  .TransactSQL,
                                                  .Turing,
                                                  .TypeScript,
                                                  .Vala_Genie,
                                                  .VBScript,
                                                  .Verilog,
                                                  .VHDL,
                                                  .VimL,
                                                  .VisualBasicNET,
                                                  .WebDNA,
                                                  .Whitespace,
                                                  .X10,
                                                  .xBase,
                                                  .XBasePP,
                                                  .Xen,
                                                  .XPL,
                                                  .XSLT,
                                                  .XQuery,
                                                  .yacc,
                                                  .Yorick,
                                                  .Zshell
    ]
    
    case
    
    None = "None",
    ABAP = "ABAP",
    ABC = "ABC",
    ActionScript = "ActionScript",
    Ada = "Ada",
    AgilentVEE = "Agilent VEE",
    Algol = "Algol",
    Alice = "Alice",
    Angelscript = "Angelscript",
    Apex = "Apex",
    APL = "APL",
    AppleScript = "AppleScript",
    Arc = "Arc",
    Arduino = "Arduino",
    ASP = "ASP",
    AspectJ = "AspectJ",
    Assembly = "Assembly",
    ATLAS = "ATLAS",
    Augeas = "Augeas",
    AutoHotkey = "AutoHotkey",
    AutoIt = "AutoIt",
    AutoLISP = "AutoLISP",
    Automator = "Automator",
    Avenue = "Avenue",
    Awk = "Awk",
    Bash = "Bash",
    VisualBasic = "(Visual) Basic",
    bc = "bc",
    BCPL = "BCPL",
    BETA = "BETA",
    BlitzMax = "BlitzMax",
    Boo = "Boo",
    BourneShell = "Bourne Shell",
    Bro = "Bro",
    C = "C",
    CShell = "C Shell",
    CSharp = "C#",
    CPP = "C++",
    CPP_CLI = "C++/CLI",
    COmega = "C-Omega",
    Caml = "Caml",
    Ceylon = "Ceylon",
    CFML = "CFML",
    cg = "cg",
    Ch = "Ch",
    CHILL = "CHILL",
    CIL = "CIL",
    CL = "CL (OS/400)",
    Clarion = "Clarion",
    Clean = "Clean",
    Clipper = "Clipper",
    Clojure = "Clojure",
    CLU = "CLU",
    COBOL = "COBOL",
    Cobra = "Cobra",
    CoffeeScript = "CoffeeScript",
    ColdFusion = "ColdFusion",
    COMAL = "COMAL",
    CommonLisp = "Common Lisp",
    Coq = "Coq",
    cT = "cT",
    Curl = "Curl",
    D = "D",
    Dart = "Dart",
    DCL = "DCL",
    DCPU_ASM = "DCPU-16 ASM",
    Delphi_ObjectPascal = "Delphi/Object Pascal",
    DiBOL = "DiBOL",
    Dylan = "Dylan",
    E = "E",
    eC = "eC",
    Ecl = "Ecl",
    ECMAScript = "ECMAScript",
    EGL = "EGL",
    Eiffel = "Eiffel",
    Elixir = "Elixir",
    EmacsLisp = "Emacs Lisp",
    Erlang = "Erlang",
    Etoys = "Etoys",
    Euphoria = "Euphoria",
    EXEC = "EXEC",
    FSharp = "F#",
    Factor = "Factor",
    Falcon = "Falcon",
    Fancy = "Fancy",
    Fantom = "Fantom",
    Felix = "Felix",
    Forth = "Forth",
    Fortran = "Fortran",
    Fortress = "Fortress",
    VisualFoxPro = "(Visual) FoxPro",
    Gambas = "Gambas",
    GNUOctave = "GNU Octave",
    Go = "Go",
    GoogleAppsScript = "Google AppsScript",
    Gosu = "Gosu",
    Groovy = "Groovy",
    Haskell = "Haskell",
    haXe = "haXe",
    Heron = "Heron",
    HPL = "HPL",
    HyperTalk = "HyperTalk",
    Icon = "Icon",
    IDL = "IDL",
    Inform = "Inform",
    InformixGL = "Informix-4GL",
    INTERCAL = "INTERCAL",
    Io = "Io",
    Ioke = "Ioke",
    J = "J",
    JSharp = "J#",
    JADE = "JADE",
    Java = "Java",
    JavaFXScript = "Java FX Script",
    JavaScript = "JavaScript",
    JScript = "JScript",
    JScriptNET = "JScript.NET",
    Julia = "Julia",
    KornShell = "Korn Shell",
    Kotlin = "Kotlin",
    LabVIEW = "LabVIEW",
    LadderLogic = "Ladder Logic",
    Lasso = "Lasso",
    Limbo = "Limbo",
    Lingo = "Lingo",
    Lisp = "Lisp",
    Logo = "Logo",
    Logos = "Logos (iOS Hacker)",
    Logtalk = "Logtalk",
    LotusScript = "LotusScript",
    LPC = "LPC",
    Lua = "Lua",
    Lustre = "Lustre",
    M4 = "M4",
    MAD = "MAD",
    Magic = "Magic",
    Magik = "Magik",
    Malbolge = "Malbolge",
    MANTIS = "MANTIS",
    Maple = "Maple",
    Mathematica = "Mathematica",
    MATLAB = "MATLAB",
    Max_MSP = "Max/MSP",
    MAXScript = "MAXScript",
    MEL = "MEL",
    Mercury = "Mercury",
    Mirah = "Mirah",
    Miva = "Miva",
    ML = "ML",
    Monkey = "Monkey",
    ModulaTwo = "Modula-2",
    ModulaThree = "Modula-3",
    MOO = "MOO",
    Moto = "Moto",
    MSDOSBatch = "MS-DOS Batch",
    MUMPS = "MUMPS",
    NATURAL = "NATURAL",
    Nemerle = "Nemerle",
    Nimrod = "Nimrod",
    NQC = "NQC",
    NSIS = "NSIS",
    Nu = "Nu",
    NXTG = "NXT-G",
    Oberon = "Oberon",
    ObjectRexx = "Object Rexx",
    ObjectiveC = "Objective-C",
    ObjectiveJ = "Objective-J",
    OCaml = "OCaml",
    Occam = "Occam",
    ooc = "ooc",
    Opa = "Opa",
    OpenCL = "OpenCL",
    OpenEdgeABL = "OpenEdge ABL",
    OPL = "OPL",
    Oz = "Oz",
    Paradox = "Paradox",
    Parrot = "Parrot",
    Pascal = "Pascal",
    Perl = "Perl",
    PHP = "PHP",
    Pike = "Pike",
    PILOT = "PILOT",
    PL_I = "PL/I",
    PL_SQL = "PL/SQL",
    Pliant = "Pliant",
    PostScript = "PostScript",
    POV_Ray = "POV-Ray",
    PowerBasic = "PowerBasic",
    PowerScript = "PowerScript",
    PowerShell = "PowerShell",
    Processing = "Processing",
    Prolog = "Prolog",
    Puppet = "Puppet",
    PureData = "Pure Data",
    Python = "Python",
    Q = "Q",
    R = "R",
    Racket = "Racket",
    REALBasic = "REALBasic",
    REBOL = "REBOL",
    Revolution = "Revolution",
    REXX = "REXX",
    RPG = "RPG (OS/400)",
    Ruby = "Ruby",
    Rust = "Rust",
    S = "S",
    S_PLUS = "S-PLUS",
    SAS = "SAS",
    Sather = "Sather",
    Scala = "Scala",
    Scheme = "Scheme",
    Scilab = "Scilab",
    Scratch = "Scratch",
    sed = "sed",
    Seed7 = "Seed7",
    Slf = "Self",
    Shell = "Shell",
    SIGNAL = "SIGNAL",
    Simula = "Simula",
    Simulink = "Simulink",
    Slate = "Slate",
    Smalltalk = "Smalltalk",
    Smarty = "Smarty",
    SPARK = "SPARK",
    SPSS = "SPSS",
    SQR = "SQR",
    Squeak = "Squeak",
    Squirrel = "Squirrel",
    StandardML = "Standard ML",
    Suneido = "Suneido",
    SuperCollider = "SuperCollider",
    Swift = "Swift",
    TACL = "TACL",
    Tcl = "Tcl",
    Tex = "Tex",
    thinBasic = "thinBasic",
    TOM = "TOM",
    TransactSQL = "Transact-SQL",
    Turing = "Turing",
    TypeScript = "TypeScript",
    Vala_Genie = "Vala/Genie",
    VBScript = "VBScript",
    Verilog = "Verilog",
    VHDL = "VHDL",
    VimL = "VimL",
    VisualBasicNET = "Visual Basic .NET",
    WebDNA = "WebDNA",
    Whitespace = "Whitespace",
    X10 = "X10",
    xBase = "xBase",
    XBasePP = "XBase++",
    Xen = "Xen",
    XPL = "XPL",
    XSLT = "XSLT",
    XQuery = "XQuery",
    yacc = "yacc",
    Yorick = "Yorick",
    Zshell = "Z shell"
 
}
